### ISSUE TITLE
Advanced CSS Master - Jonas Schmedtman

### ISSUE THREAD

**Issue by camika** [camika/advanced-CSS-Master#1]
C:\Users\User\Desktop\advanced CSS - udemy\New folder\advanced-css-course-master\Natours\starter>npm run prefix:css

> natours@1.0.0 prefix:css C:\Users\User\Desktop\advanced CSS - udemy\New folder\advanced-css-course-master\Natours\starter
> postcss --use autoprefixer -b "last 10 versions" css/style.concat.css -o css/style.prefix.css

TypeError: Patterns must be a string or an array of strings
    at assertPatternsInput (C:\Users\User\Desktop\advanced CSS - udemy\New folder\advanced-css-course-master\Natours\starter\node_modules\globby\index.js:14:9)
    at generateGlobTasks (C:\Users\User\Desktop\advanced CSS - udemy\New folder\advanced-css-course-master\Natours\starter\node_modules\globby\index.js:20:2)
    at module.exports (C:\Users\User\Desktop\advanced CSS - udemy\New folder\advanced-css-course-master\Natours\starter\node_modules\globby\index.js:74:15)
    at Promise.resolve.then (C:\Users\User\Desktop\advanced CSS - udemy\New folder\advanced-css-course-master\Natours\starter\node_modules\postcss-cli\index.js:53:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! natours@1.0.0 prefix:css: `postcss --use autoprefixer -b "last 10 versions" css/style.concat.css -o css/style.prefix.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the natours@1.0.0 prefix:css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-09-11T10_53_42_045Z-debug.log

I cannot understand why did it appear ? when I put it into strings. Help please

**Comment by camika** [comment]
i use Windows 10
